### ISSUE TITLE
type mismatch during cross-compilation

### ISSUE THREAD

**Issue by master-hax** [cholcombe973/libnfs#16]
hi, thanks for making this awesome library. i am having an issue when cross-compiling for android. specifically this line:
https://github.com/cholcombe973/libnfs/blob/02ff5edfe12317a166dee17d014bcff1c37295ee/src/lib.rs#L466
the compiler expects it to be `u8` instead of `i8` when building for arm64 & linking with the android ndk compiler i.e.
```
buf.as_mut_ptr() as *mut u8,
```
but when compiling for my local box (ubuntu x86_64), the compiler wants `i8`

is this something we can set automatically during the build? it seems to run just fine with this one tweak.

**Comment by cholcombe973** [comment]
Yeah this should be possible with some compile time flags around the
architecture.

**Comment by cholcombe973** [comment]
To expand upon this a little, what could be done is we could mark that entire unsafe{} block with a conditional compile flag such as: 
```
#[cfg(target_os = "linux")]
unsafe {
   ... existing code
}

#[cfg(target_os = "android")]
unsafe {
    .. android specific code
}
```
I would try playing around with that and see where that gets you.

**Comment by master-hax** [comment]
looks like we get this for free from the `c_char` type in [core:ffi](https://doc.rust-lang.org/src/core/ffi/mod.rs.html#91)

**Comment by master-hax** [comment]
opened PR https://github.com/cholcombe973/libnfs/pull/17
