### ISSUE TITLE
pread API has a potential buffer overrun

### ISSUE THREAD

**Issue by jsgf** [cholcombe973/libnfs#4]
`pread()` doesn't check that `buffer.capacity()` is >= `count`. 

I think it would be a better API to just make pread do the allocation and return a `Vec<u8>`:
```
fn pread(&self, count: u64, offset: u64) -> Result<Vec<u8>> {
```

**Comment by cholcombe973** [comment]
Ah yeah good catch.  I missed that.  I might have to also fix this in the gluster wrapper.  I cribbed a lot of the code from there. I think what I was thinking with this function is that you could reuse a buffer if you kept passing it to the pread instead of having an allocation per read.

**Comment by jsgf** [comment]
Yeah, I figured that would be the rationale, but I think that would be better expressed as `&mut [u8]` - as a `Vec` it always goes from the beginning of the vec with `buffer.as_mut_ptr()`.

**Comment by cholcombe973** [comment]
Yeah I'm fine with changing it

**Comment by cholcombe973** [comment]
#6 takes care of this
